### ISSUE TITLE
Full-width design is hard to read

### ISSUE THREAD

**Issue by lorenzhs** [etcet/HNES#140]
First, thanks for this useful extension!

I find the style quite hard to read, though:
- setting the main container to 100% width makes it hard to read long comments
- the large amount of vertical space between comments makes it harder to keep track of the nesting
- your choice of fonts doesn't look very nice on my system

Would you consider making the style tweaks optional? I see you have an options page on your To-Do list already.

**Comment by etcet** [comment]
The width of individual comments is actually the same as regular HN.  I agree they shouldn't be 100% width, please show a screenshot if that is the case.

There is a large amount of space between comments! That's a thing I hadn't really noticed but I see what you mean. I'll mark this as a bug so that can be fixed.

I'll also look into changing the fonts back to defaults. Let me know in a screenshot how bad it looks for you and that'll move that request along faster if it's truly awful.

**Comment by etcet** [comment]
Sorry, not going to change the full width but the spacing between comments and fonts have been changed.

**Comment by lorenzhs** [comment]
Sure, thanks for the fixes :)
