### ISSUE TITLE
Voting not working

### ISSUE THREAD

**Issue by zymurgypg** [etcet/HNES#150]
Hello,

It appears the latest version of Chrome has broken the ability to vote on submissions and comments. 

I am using Version 63.0.3239.86 (Official Build) (64-bit). 

Thanks!

**Comment by acnebs** [comment]
Seeing the same behaviour (no voting buttons anywhere) on Chrome Canary (65.0.3302.0). Additionally, (and not sure if this is the right issue to bring this up because I'm not sure it's related, but) the HN logo in the top left is showing a blank box instead of the actual logo. In the console, I get the error:

```
Refused to load the image 'data:image/png;base64,[...]' 
because it violates the following Content Security Policy directive: 
"default-src 'self'". Note that 'img-src' was not explicitly set, 
so 'default-src' is used as a fallback.
```

**Comment by kiddico** [comment]
Well the required change is as dumb as it seems.
[See my commit for the required change](https://github.com/kiddico/HNES/commit/cfdd5b59f68af10e438b56501808045293d9e815). I tested on Firefox and Chromes latest versions so maybe someone can test on other platforms to be sure I've not broken anything. 
I'll be making a pull request, but my last one is still sitting there so it may be a while.

**Comment by Niek** [comment]
Seems to be fixed in https://github.com/etcet/HNES/pull/153 (merged)

@etcet would it be possible to release a new version in the Chrome store?

**Comment by etcet** [comment]
Gah, thanks @Niek, it was stuck as a draft.
